@AllHandsMaio2024_HostAddress = https://localhost:7147

GET {{AllHandsMaio2024_HostAddress}}/

###

GET {{AllHandsMaio2024_HostAddress}}/products

###

POST {{AllHandsMaio2024_HostAddress}}/products
Content-Type: application/json

{ 
  "Name": "iPhone 18", 
  "Price": 20999.00,
  "BrandId": null
}

###

GET {{AllHandsMaio2024_HostAddress}}/products/9?includeBrand=false

###

PUT {{AllHandsMaio2024_HostAddress}}/products/8
Content-Type: application/json

{
  "Name": "teste 2", 
  "Price": 7999.00,
  "BrandId": 1
}

###

DELETE {{AllHandsMaio2024_HostAddress}}/products/7

###
